stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

build:
  stage: build
  image: python:3.9
  script:
    - pip install build
    - VERSION=$(date +%y.%m.%d.%H%M)
    - sed -i "s/__version__ = '.*'/__version__ = '$VERSION'/" subtitld/__init__.py
    - python -m build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy_testpypi:
  stage: deploy
  image: python:3.9
  only:
    - branches
  except:
    - master
  script:
    - pip install twine
    - twine upload --repository testpypi dist/* -u __token__ -p "$TESTPYPI_TOKEN" --verbose
  dependencies:
    - build

deploy_pypi:
  stage: deploy
  image: python:3.9
  only:
    - master
  script:
    - pip install twine
    - twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
  dependencies:
    - build

build_appimage:
  stage: deploy
  image: ubuntu:22.04
  script:
    - export VERSION_NUMBER=$(date +%y.%m.%d.%H%M)
    - "sed -i \"s/version: 22.09.01.01/version: $VERSION_NUMBER/\" AppImageBuilder.yml"
    - apt-get update -qy
    - apt-get install -y sshpass
    - DEBIAN_FRONTEND=noninteractive apt-get install -y wget python3-pip gtk-update-icon-cache libgdk-pixbuf-2.0-0 squashfs-tools zsync libglib2.0-bin ffmpeg
    - mkdir -p ~/.local/bin
    - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O ~/.local/bin/appimagetool
    - chmod +x ~/.local/bin/appimagetool
    - python3 --version
    - python3 -m pip install appimage-builder
    - python3 -m pip install dist/*.whl
    - python3 -m pip install PyInstaller
    - python3 -m PyInstaller subtitld.spec
    - appimage-builder --skip-test --recipe AppImageBuilder.yml
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no Subtitld*.AppImage subtitld-builds@62.72.63.228:/home/subtitld-builds/htdocs/builds.subtitld.org/appimage/
  artifacts:
    paths:
      - Subtitld-*.AppImage
    expire_in: 1 month

build_windows:
  image: cheaterman/pyinstaller-windows:latest
  stage: deploy
  script:
    - export VERSION_NUMBER=`date +%y.%m.%d.%H%M`
    - apt-get update -qy
    - apt-get install -y nsis openssh-client sshpass unzip zip
    - wget https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip --no-check-certificate
    - unzip ffmpeg-release-essentials.zip
    - export PATH=$PATH:$(pwd)/ffmpeg-*-essentials_build/bin
    - wine pip3 install dist/*.whl
    - wine pip3 install -U pyinstaller pywin32
    - wine python -m PyInstaller subtitld-windows.spec
    - cd dist && zip -r ../Subtitld-Portable-${VERSION_NUMBER}.zip Subtitld/ && cd ..
    - makensis nsis-installer.nsi
    - mv "Subtitld-Setup.exe" "Subtitld-Setup-${VERSION_NUMBER}.exe"
    - export SSHPASS=$USER_PASS
    - sshpass -e scp -o stricthostkeychecking=no Subtitld-Portable-*.zip Subtitld-Setup-*.exe subtitld-builds@62.72.63.228:/home/subtitld-builds/htdocs/builds.subtitld.org/windows/
  artifacts:
    paths:
      - Subtitld-Portable-*.zip
      - Subtitld-Setup-*.exe
    expire_in: 1 month
