stages:
  - build
  - deploy
  - package

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

build:
  stage: build
  image: python:3.9
  script:
    - pip install build
    - VERSION=$(date +%y.%m.%d.%H%M)
    - sed -i "s/__version__ = '.*'/__version__ = '$VERSION'/" subtitld/__init__.py
    - python -m build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy_testpypi:
  stage: deploy
  image: python:3.9
  only:
    - branches
  except:
    - master
  script:
    - pip install twine
    - twine upload --repository testpypi dist/* -u __token__ -p "$TESTPYPI_TOKEN" --verbose
  dependencies:
    - build

deploy_pypi:
  stage: deploy
  image: python:3.9
  only:
    - master
  script:
    - pip install twine
    - twine upload dist/* -u __token__ -p "$PYPI_TOKEN"
  dependencies:
    - build

build_appimage:
  stage: package
  image: ubuntu:22.04
  script:
    - apt-get update
    - apt-get install -y python3 python3-pip wget file libfuse2
    - chmod +x build-appimage.sh
    - ./build-appimage.sh
  artifacts:
    paths:
      - Subtitld-*.AppImage
    expire_in: 1 month
