"""USF (Universal Subtitle Format) reader/writer."""


import base64
import os

from bs4 import BeautifulSoup, NavigableString
import subtitld.modules.timecode as timecode


USF_BASE_MARKUP = '''<!-- USF file generated by Subtitld -->
<USFSubtitles version="1.0">
    <metadata></metadata>
    <styles></styles>
</USFSubtitles>'''


def _extract_inline_text(tag):
    """Return the text of a tag, converting <br/> to \\n and flattening inline formatting."""
    parts = []
    for child in tag.children:
        if isinstance(child, NavigableString):
            parts.append(str(child))
            continue
        if child.name == 'br':
            parts.append('\n')
            continue
        parts.append(_extract_inline_text(child))
    return ''.join(parts).strip()


def _parse_numeric(value, caster):
    try:
        return caster(value)
    except (TypeError, ValueError):
        return None


class USFReader():
    """USFReader class"""
    def __init__(self, *args, **kwargs):
        super(USFReader, self).__init__(*args, **kwargs)
        self.metadata = {}
        self.language = None
        self.speakers = {}  # name -> {'color': '#RRGGBB'}
        self.has_embedded_images = False
        self.has_embedded_audio_clips = False

    def detect(self, content):
        """Function to return if this is a USF file"""
        return '<usfsubtitles' in content.lower()

    def read(self, content):
        """Parse USF content and return a list of subtitle dicts.

        Populates self.metadata, self.language and self.speakers as a side
        effect so the caller can reflect title/author/date/language and the
        per-speaker colors back into session state.
        """
        self.metadata = {}
        self.language = None
        self.speakers = {}
        self.has_embedded_images = False
        self.has_embedded_audio_clips = False

        soup = BeautifulSoup(content, features="xml")

        meta = soup.find('metadata')
        if meta:
            for key in ('title', 'date'):
                tag = meta.find(key)
                if tag and tag.text:
                    self.metadata[key] = tag.text.strip()
            lang = meta.find('language')
            if lang and lang.attrs.get('code'):
                self.language = lang.attrs['code']
            author = meta.find('author')
            if author:
                name = author.find('name')
                if name and name.text:
                    self.metadata['author'] = name.text.strip()

        for style in soup.select('styles > style'):
            name = style.attrs.get('name')
            if not name or name == 'Default':
                continue
            entry = {}
            fontstyle = style.find('fontstyle')
            if fontstyle and fontstyle.attrs.get('color'):
                entry['color'] = fontstyle.attrs['color']
            avatar = style.find('avatar')
            if avatar and avatar.attrs.get('encoding') == 'base64' and avatar.text:
                try:
                    entry['image_bytes'] = base64.b64decode(avatar.text.strip())
                    self.has_embedded_images = True
                except Exception:
                    pass
            dub_elem = style.find('dubbing')
            if dub_elem:
                dub_data = {}
                for key in ('engine', 'voice'):
                    if key in dub_elem.attrs:
                        dub_data[key] = dub_elem.attrs[key]
                for key in ('rate', 'pitch'):
                    if key in dub_elem.attrs:
                        parsed = _parse_numeric(dub_elem.attrs[key], int)
                        if parsed is not None:
                            dub_data[key] = parsed
                if dub_data:
                    entry['dubbing'] = dub_data
            if entry:
                self.speakers[name] = entry

        blocks = soup.find_all('subtitles')
        if not blocks:
            return []

        primary_block = blocks[0]
        primary_lang = self._block_language(primary_block)
        if primary_lang and not self.language:
            self.language = primary_lang

        subtitles_list = []
        for element in primary_block.find_all('subtitle', recursive=False):
            entry = self._parse_subtitle(element)
            if entry:
                subtitles_list.append(entry)

        for block in blocks[1:]:
            lang = self._block_language(block)
            if not lang:
                continue
            tr_subs = block.find_all('subtitle', recursive=False)
            for primary_sub, tr_sub in zip(subtitles_list, tr_subs):
                text_tag = tr_sub.find('text') or tr_sub.find('karaoke')
                if text_tag is None:
                    continue
                primary_sub.setdefault('translations', {})[lang] = _extract_inline_text(text_tag)

        return subtitles_list

    def _block_language(self, block):
        lang = block.find('language')
        if lang and lang.attrs.get('code'):
            return lang.attrs['code']
        return None

    def _parse_subtitle(self, element):
        if 'start' not in element.attrs or 'stop' not in element.attrs:
            return None

        subtitle = {
            'start': timecode.Timecode('1000', element.attrs['start']).float,
            'end': timecode.Timecode('1000', element.attrs['stop']).float,
        }

        text_tag = element.find('text') or element.find('karaoke')
        subtitle['text'] = _extract_inline_text(text_tag) if text_tag else ''
        subtitle['speaker'] = (text_tag.attrs.get('speaker') if text_tag else None) or 'A'

        dubs = []
        for dub_elem in element.find_all('dubbing', recursive=False):
            dub = {}
            for key, value in dub_elem.attrs.items():
                dub[key] = value
            for key in ('start', 'end'):
                if key in dub:
                    parsed = _parse_numeric(dub[key], float)
                    if parsed is not None:
                        dub[key] = parsed
            for key in ('rate', 'pitch'):
                if key in dub:
                    parsed = _parse_numeric(dub[key], int)
                    if parsed is not None:
                        dub[key] = parsed
            data_tag = dub_elem.find('data')
            if data_tag and data_tag.attrs.get('encoding') == 'base64' and data_tag.text:
                try:
                    dub['_embedded_bytes'] = base64.b64decode(data_tag.text.strip())
                    dub['_embedded_format'] = data_tag.attrs.get('format', 'wav')
                    self.has_embedded_audio_clips = True
                except Exception:
                    pass
            # Per-subclip data (independent subclips schema — see
            # dub_clip.py). Each <subclip> carries source coords (start,
            # end), timeline offset (offset), and an optional rate/raw_path
            # for ffmpeg-stretched subclips. Without persisting these the
            # split/stretch a user did is silently discarded on reload.
            segs = []
            for seg_elem in dub_elem.find_all('subclip', recursive=False):
                seg = {}
                for key, value in seg_elem.attrs.items():
                    seg[key] = value
                for key in ('start', 'end', 'offset'):
                    if key in seg:
                        parsed = _parse_numeric(seg[key], float)
                        if parsed is not None:
                            seg[key] = parsed
                if 'rate' in seg:
                    parsed = _parse_numeric(seg['rate'], int)
                    if parsed is not None:
                        seg['rate'] = parsed
                seg.setdefault('type', 'audio')
                segs.append(seg)
            if segs:
                dub['segments'] = segs
            dubs.append(dub)
        if dubs:
            subtitle['dubbing'] = dubs

        return subtitle


class USFWriter():
    """USFWriter class"""
    def __init__(self, *args, **kwargs):
        super(USFWriter, self).__init__(*args, **kwargs)

    def write(self, subtitles, speakers=None, language=None, metadata=None,
              embed_audio_clips=False):
        """Serialize subtitles to USF XML.

        Parameters:
          subtitles: list of subtitle dicts (from session.SUBTITLE['segments']).
          speakers:  dict name -> {'color': '#RRGGBB', 'image_bytes': bytes, ...}.
                     Emits one <style> per speaker; writes `speaker` + `style` on
                     <text>. If a speaker has `image_bytes`, embeds it inside the
                     <style> as <avatar encoding="base64" format="png">…</avatar>.
          language:  ISO language code for the primary <subtitles> block.
          metadata:  dict with optional 'title', 'author', 'date' keys.
          embed_audio_clips: if True, reads each dub's WAV file from disk and
                     embeds base64 bytes as <data encoding="base64"> inside the
                     <dubbing> element.
        """
        speakers = speakers or {}
        metadata = metadata or {}

        usf = BeautifulSoup(USF_BASE_MARKUP, 'lxml-xml')

        meta_tag = usf.find('metadata')
        if 'title' in metadata:
            title = usf.new_tag('title')
            title.string = str(metadata['title'])
            meta_tag.append(title)
        author = usf.new_tag('author')
        name = usf.new_tag('name')
        name.string = str(metadata.get('author', 'Subtitld'))
        author.append(name)
        meta_tag.append(author)
        if language:
            lang_tag = usf.new_tag('language')
            lang_tag['code'] = language
            meta_tag.append(lang_tag)
        if 'date' in metadata:
            date = usf.new_tag('date')
            date.string = str(metadata['date'])
            meta_tag.append(date)

        styles_tag = usf.find('styles')

        default_style = usf.new_tag('style')
        default_style['name'] = 'Default'
        default_fontstyle = usf.new_tag('fontstyle', color='#EEEEFF', face='Arial', size='24', family='Arial')
        default_fontstyle['outline-color'] = '#5555FF'
        default_style.append(default_fontstyle)
        default_position = usf.new_tag('position', alignment='BottomCenter')
        default_position['relative-to'] = 'Window'
        default_position['vertical-margin'] = '10%'
        default_style.append(default_position)
        styles_tag.append(default_style)

        for speaker_name, speaker_data in speakers.items():
            if speaker_name == 'Default':
                continue
            style = usf.new_tag('style')
            style['name'] = speaker_name
            color = speaker_data.get('color') if isinstance(speaker_data, dict) else None
            if color:
                fontstyle = usf.new_tag('fontstyle')
                fontstyle['color'] = color
                style.append(fontstyle)
            image_bytes = speaker_data.get('image_bytes') if isinstance(speaker_data, dict) else None
            if image_bytes:
                avatar = usf.new_tag('avatar')
                avatar['encoding'] = 'base64'
                avatar['format'] = 'png'
                avatar.string = base64.b64encode(image_bytes).decode('ascii')
                style.append(avatar)
            dubbing_settings = speaker_data.get('dubbing') if isinstance(speaker_data, dict) else None
            if isinstance(dubbing_settings, dict):
                dub_tag = usf.new_tag('dubbing')
                for key in ('engine', 'voice'):
                    val = dubbing_settings.get(key)
                    if val:
                        dub_tag[key] = str(val)
                for key in ('rate', 'pitch'):
                    val = dubbing_settings.get(key)
                    if val is not None:
                        dub_tag[key] = str(val)
                if dub_tag.attrs:
                    style.append(dub_tag)
            styles_tag.append(style)

        primary = usf.new_tag('subtitles')
        if language:
            lang_tag = usf.new_tag('language')
            lang_tag['code'] = language
            primary.append(lang_tag)
        usf.find('USFSubtitles').append(primary)

        for subtitle in subtitles:
            primary.append(self._build_subtitle(usf, subtitle, speakers, embed_audio_clips=embed_audio_clips))

        translation_languages = []
        for subtitle in subtitles:
            for lang in subtitle.get('translations', {}):
                if lang and lang not in translation_languages and lang != language:
                    translation_languages.append(lang)

        for tr_lang in translation_languages:
            block = usf.new_tag('subtitles')
            lang_tag = usf.new_tag('language')
            lang_tag['code'] = tr_lang
            block.append(lang_tag)
            for subtitle in subtitles:
                block.append(self._build_subtitle(
                    usf,
                    subtitle,
                    speakers,
                    text_override=subtitle.get('translations', {}).get(tr_lang, ''),
                    include_dubs=False,
                ))
            usf.find('USFSubtitles').append(block)

        return str(usf)

    def _build_subtitle(self, usf, subtitle, speakers, text_override=None, include_dubs=True, embed_audio_clips=False):
        new_sub = usf.new_tag(
            'subtitle',
            start=str(timecode.Timecode('1000', start_seconds=subtitle['start'], fractional=True)),
            stop=str(timecode.Timecode('1000', start_seconds=subtitle['end'], fractional=True)),
        )

        text_tag = usf.new_tag('text')
        speaker = subtitle.get('speaker', 'A')
        if speaker:
            text_tag['speaker'] = speaker
            if speaker in speakers:
                text_tag['style'] = speaker

        text_value = subtitle.get('text', '') if text_override is None else text_override
        self._append_text_with_breaks(usf, text_tag, text_value)
        new_sub.append(text_tag)

        if include_dubs:
            for dub in subtitle.get('dubbing', []):
                dub_tag = usf.new_tag('dubbing')
                for key in ('engine', 'path', 'uid', 'voice', 'raw_path'):
                    if key in dub and dub[key] is not None:
                        dub_tag[key] = str(dub[key])
                for key in ('start', 'end', 'rate', 'pitch'):
                    if key in dub and dub[key] is not None:
                        dub_tag[key] = str(dub[key])
                # Persist independent subclips (the split/stretch list).
                # Without these elements the schema collapses on reload to
                # a single subclip synthesised from `dub['path']` — every
                # split or per-subclip stretch the user made is lost.
                for seg in dub.get('segments', []) or []:
                    seg_tag = usf.new_tag('subclip')
                    for key in ('type', 'path', 'raw_path'):
                        if key in seg and seg[key] is not None:
                            seg_tag[key] = str(seg[key])
                    for key in ('start', 'end', 'offset'):
                        if key in seg and seg[key] is not None:
                            seg_tag[key] = str(seg[key])
                    if seg.get('rate') is not None:
                        seg_tag['rate'] = str(seg['rate'])
                    dub_tag.append(seg_tag)
                if embed_audio_clips:
                    path = dub.get('path')
                    if path and os.path.isfile(path):
                        try:
                            with open(path, 'rb') as f:
                                raw = f.read()
                            data_tag = usf.new_tag('data')
                            data_tag['encoding'] = 'base64'
                            data_tag['format'] = os.path.splitext(path)[1].lstrip('.').lower() or 'wav'
                            data_tag.string = base64.b64encode(raw).decode('ascii')
                            dub_tag.append(data_tag)
                        except Exception:
                            pass
                new_sub.append(dub_tag)

        return new_sub

    def _append_text_with_breaks(self, usf, text_tag, value):
        if not value:
            return
        lines = str(value).split('\n')
        for idx, line in enumerate(lines):
            if idx:
                text_tag.append(usf.new_tag('br'))
            if line:
                text_tag.append(NavigableString(line))
